### ISSUE TITLE
Really nice idea!

### ISSUE THREAD

**Issue by z** [manmohanjit1/mybb_watch#1]
Howdy,

I stumbled across your script because I was frustrated with the [lack of a] pipeline for pushing out theme/template updates.

I noticed you've only scoped to template files. Any plans to support CSS?

**Comment by z** [comment]
I've implemented it in a fork here https://github.com/z/mybb-theme-bridge

**Comment by manmohanjit** [comment]
I actually reworked it and included it into my Laravel project, will probably re-release it later.

**Comment by z** [comment]
Sounds good, will keep an eye out.
